### PR TITLE
Remove docker and Vagrant support

### PR DESCRIPTION
**Pull request by Toxantron**
There were lots of complaints about docker and the image was fairly old. I am glad @chrisns has volunteered to maintain the docker image in the future.

### CODE REVIEW

**Comment by DewaldDeJager** [comment]
@Toxantron Any activity on this? It looks like @chrisns may have made a hard fork with no intention of merging back here. I say this because he's squashed most commits, licensed it to himself and made a lot of other changes: https://github.com/chrisns/scrumonline

If you'd like Docker support in this project and want a volunteer, I'm more than happy to help. Just don't want to do duplicate work.

**Comment by DewaldDeJager** [comment]
Ah, I see what's happened. The work has been done but in a completely separate repo with this as a submodule. It's not ideal but I guess it works.

**Comment by chrisns** [comment]
hey @DewaldDeJager, yeah the submodule was a gross hack, but it means @dependabot keeps it current and rebuilds the container for me so that its always current with this repo

**Comment by chrisns** [comment]
but yeah, not a fork, and I probably should have named the repo something better, but it got linked to and I didn't want to 404 those.
sorry for any confusion caused

**Comment by Monpoke** [comment]
Hello, I made a Helm chart from your both repositories! 
I should improve it next days with persistence support and external database.

https://github.com/OS4run/helm-charts/tree/master/charts/scrumonline

Tell me what do you think about it. :-)

**Comment by chrisns** [comment]
hey @Monpoke looks great, feel free to pr my repo if you like? happy to add you as a contributor to keep docker and k8s stuff in place. I still need to get round to documenting the knative bodge I did to run it in google cloud run

thoughts on the template itself, if you're running it properly in k8s, it'd be good to separate out the mysql into a statefulset and service and back it with a pvc, or if you don't want to bother with that, fix the `replica` count at 1 since anything more is going to lead to an undesirable split of traffic between where the data is.

**Pull request merged**
