### PR TITLE
Update plugins.js

### PR DESCRIPTION
**Pull request by Daiben**
Tiny change it's possible to use organisations if you use define in the repo field Company/Repo

### CODE REVIEW

**Comment by Toxantron** [comment]
Thanks, that is in fact an easy solution. The idea is to enter **Toxantron/scrumonline** into the repo field, right?

I like it, but we should adjust the *view* to make this more transparent. Maybe by adding a watermark to [the input](https://github.com/Toxantron/scrumonline/blob/master/src/templates/github_source.html#L21) and probably reording the inputs to make clear that user and password are only required for private repos.

Feel free to do this by pushing more commits to the PR, otherwise I will do it later or tomorrow.

**Comment by Daiben** [comment]
Do you mind if i make all the text on the pages configurable?

I'm going to change some parts of your code for the company i work for.

**Comment by Toxantron** [comment]
You are free to change what you want. It is under the Apache license. ;-)

And if it looks good I will probably merge it. :-)

**Comment by Toxantron** [comment]
Thinking about it, it is probably better if you fork the project and modify the files. For example removing the Impressum etc. Otherwise the config probably becomes pretty big.

And if you keep my version (upstream) on a branch we can still exchange functionality. ;-)

**Comment by Toxantron** [comment]
On the other side it is probably just the text on the front page, right. I think we can make this configurable.

**Pull request merged**
