### PR TITLE
Jira integration #41

### PR DESCRIPTION
**Pull request by filipgolonka**
@Toxantron 

Done

### CODE REVIEW

**Comment by Toxantron** [comment]
Thanks, that was fast and the server side controller eliminates the CORS problem.

**Comment by Toxantron** [comment]
The only problem is, that [scrumpoker.online](www.scrumpoker.online) is only _http_ and therefore sending JIRA credentials is a security risk. That's why the other plugins fully operate on the client side.

Suggestion: I will add a note pointing towards your docs saying that JIRA is disabled in the public demo for security concerns, but can be activated for in-house deployment.

**or**

I finally move the page to _https_.

**Comment by Toxantron** [comment]
Reading through [SO questions](http://stackoverflow.com/questions/33742949/enable-cors-in-jira-rest-api) we seem to have no other choice than to tunnel it through the server as JIRA does not supports CORS.

**Comment by filipgolonka** [comment]
@Toxantron please hold on with merging, still there is no error handling so I need to prepare it. I'd like to get only the general review of the idea.

**Comment by Toxantron** [comment]
I like it so far. ;-)

**Comment by Toxantron** [comment]
@filipgolonka do you still need to implement error handling, or is it ready to merge?

**Comment by filipgolonka** [comment]
@Toxantron yup, I will finish it today or tomorrow :)

**Comment by Toxantron** [comment]
No hurry, I just wasn't sure if you wanted me to wait or merge. ;-)

**Comment by filipgolonka** [comment]
@Toxantron sorry for so long time without feedback - now it's ready to be merged :) please review, feedback appreciated :)

**Comment by Toxantron** [comment]
@filipgolonka thank you for your contribution.

Code itself looks fine, but I have a question about the vagrant files, since I have no experience with it (I added docker instead). Are they necessary, what do they do and did you intend to include the private RSA key?

**Comment by filipgolonka** [comment]
incorrect conflicts resolving, damn :) fixed.

**Comment by Toxantron** [comment]
Looks a lot better.

**Comment by Toxantron** [comment]
Merged! Thank you for your contribution. Since I acquired an SSL certificate I will enable it on www.scrumpoker.online for publicly accessible JIRA servers.

**Comment by Toxantron** [comment]
@filipgolonka I enabled it on the public page today. If you get a chance to validate that is is working, let me know. ;-)

**Pull request merged**
