### PR TITLE
missing comma

### PR DESCRIPTION
**Pull request by mvictoriano**
Seems to be a lack of the last comma

### CODE REVIEW

**Comment by Toxantron** [comment]
Thanks, that seems to be an undiscovered merge conflict

**Comment by mvictoriano** [comment]
Your welcome. Maybe something more its wrong because you cant chosse all
coded options in the web selector.

**Comment by Toxantron** [comment]
There is no automatism to sync the repo to the server, yet. I want to rebase this against dev and will merge it.

**Comment by Toxantron** [comment]
Both cards sets are subsets of existing card sets, so I won't include them. Sorry!

**Pull request closed without merging**
